# ----
# Site

title: ShoutOUT
description: ShoutOUT API Reference
url: https://developers.getshoutout.com
google_analytics_key: UA-41570235-15
permalink: pretty

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Documentation
    position: 1
  liteapi:
    title: Lite API
    position: 2
  coreapi:
    title: CRM API
    position: 3
  otpapi:
    title: OTP API
    position: 4
  loyaltyapi:
    title: Loyalty API
    position: 5
  rewardsapi:
    title: Rewards API
    position: 6
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
